kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dingtalk 
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dingtalk
    spec:
      containers:
        - name: dingtalk
          image: 172.16.1.170/base-image/dingtalk:20200811 
          ports:
          - containerPort: 9000
            name: port
          #command: [ "/bin/sh", "-c", "sleep 20000" ] 
      restartPolicy: Always
---
---
apiVersion: v1
kind: Service
metadata:
  name: dingtalk
  namespace: kube-system
  labels:
    name: dingtalk
spec:
  type: NodePort
  ports:
    - name: port
      port: 9000
      targetPort: 9000
      nodePort: 30900
  selector:
    app: dingtalk
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dingtalk 
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip     
spec:
  rules:
  - host: testdingtalk.shhzcj.com
    http:
      paths:
      - path: /
        backend:
          serviceName: dingtalk
          servicePort: port
